### PR TITLE
chore: migrate type tests to TSTyche

### PR DESCRIPTION
**Pull request by mrazauskas**
Thanks for using `jest-runner-tsd` and `tsd-lite` to test types. I am maintaining `tsd-lite` and helping with the runner too.

The bad news are that `tsd-lite` is being sunset. See the [deprecation notice](https://github.com/mrazauskas/tsd-lite/issues/364).

The good news: recently I published TSTyche, a mighty type testing tool. I was developing it for two years. TSTyche is using the same TypeScript's type checker to compare types. The rest is different.

Repo: https://github.com/tstyche/tstyche
Documentation: https://tstyche.org

---

First it does not require patched TypeScript package like `@tsd/typescript` to be installed. It will load the `typescript` from `node_modules` and use it for testing types. The install size of TSTyche is [install size](https://packagephobia.com/result?p=tstyche).

It is fast. Just give it a spin.

You can also test on several versions of TypeScript: `tstyche --target 4.9,current`. This command would use TypeScript 4.9 and the one from `node_modules` (the `current`).

TSTyche has `test()` and `describe()` helpers which support run mode flags like `.only`, `.skip`. Optional to use, but priceless if you have to debug something. For a small project, bare assertions are enough and you can do `expect.only` or `expect.skip` directly on them too.

And there is much more.

Most important: TSTyche is lightweight and friendly with small projects. If your project grows, there is a lot in the toolbox (;

### CODE REVIEW

**Comment by eegli** [comment]
Thanks a lot for the information, I'll have a look into migrating next week. I'm looking forward to using the helpers for type tests as well!

**Comment by mrazauskas** [comment]
Glad to hear that. Feel free to rework anything you see in this PR. Ping me if you have any questions.

By the way, TSTyche is released as beta to try it out in the real world. I am planning to release `rc` in around a month and version 1 a bit later. Of course, it might feel wrong to add beta releases to repo. Note that `tsd-lite` is in zero releases.

Some users were asking for Jest runner. That is not possible, because Jest does not support extra flags like `--target`. I could handled this via config file, but reporting results is really cumbersome. In the beginning TSTyche was a runner, but that did not work well.

Interestingly Jest and TSTyche can be used in the same file: https://tstyche.org/guide/test-runner#functional-tests

And one more detail. I got hooked by type testing while writing and contributing type tests to the Jest repo. There are around 1000 assertions right now. `jest-runner-tsd` is running them and it does good job (there is even a script to test on older version of TypeScript). At the same time I could see that we need a better tool. Two years later: Jest type tests are migrating to TSTyche.

**Comment by mrazauskas** [comment]
TSTyche 1.0.0 is just released.

@eegli Perhaps it would be possible to land this PR? Or something is missing?

**Comment by eegli** [comment]
Hey @mrazauskas, TSTyche has been added to the project as part of the latest release. So far, everything has been working solid. I might add new type tests soon and will let you know if I encounter any errors. Thanks for your work!

**Pull request closed without merging**
